// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EMMCMCStepSummary
SEXP EMMCMCStepSummary(SEXP yin, SEXP varbetain, SEXP Ain, SEXP betain, SEXP tauin, SEXP em_iterin, SEXP mcmc_iterin, SEXP min_degenein);
RcppExport SEXP _iDEA_EMMCMCStepSummary(SEXP yinSEXP, SEXP varbetainSEXP, SEXP AinSEXP, SEXP betainSEXP, SEXP tauinSEXP, SEXP em_iterinSEXP, SEXP mcmc_iterinSEXP, SEXP min_degeneinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varbetain(varbetainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Ain(AinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betain(betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type em_iterin(em_iterinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mcmc_iterin(mcmc_iterinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min_degenein(min_degeneinSEXP);
    rcpp_result_gen = Rcpp::wrap(EMMCMCStepSummary(yin, varbetain, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein));
    return rcpp_result_gen;
END_RCPP
}
// EMMCMCStepSummaryWeight
SEXP EMMCMCStepSummaryWeight(SEXP yin, SEXP varbetain, SEXP weightin, SEXP Ain, SEXP betain, SEXP tauin, SEXP em_iterin, SEXP mcmc_iterin, SEXP min_degenein);
RcppExport SEXP _iDEA_EMMCMCStepSummaryWeight(SEXP yinSEXP, SEXP varbetainSEXP, SEXP weightinSEXP, SEXP AinSEXP, SEXP betainSEXP, SEXP tauinSEXP, SEXP em_iterinSEXP, SEXP mcmc_iterinSEXP, SEXP min_degeneinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type varbetain(varbetainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weightin(weightinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Ain(AinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betain(betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type em_iterin(em_iterinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mcmc_iterin(mcmc_iterinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min_degenein(min_degeneinSEXP);
    rcpp_result_gen = Rcpp::wrap(EMMCMCStepSummaryWeight(yin, varbetain, weightin, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _iDEA_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iDEA_EMMCMCStepSummary", (DL_FUNC) &_iDEA_EMMCMCStepSummary, 8},
    {"_iDEA_EMMCMCStepSummaryWeight", (DL_FUNC) &_iDEA_EMMCMCStepSummaryWeight, 9},
    {"_iDEA_rcpp_hello_world", (DL_FUNC) &_iDEA_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_iDEA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
