# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' EM-MCMC function based on summary statistics, effect size and variance of effect size
#' @param yin Estimated beta
#' @param varbetain Variance
#' @param Ain Annotation
#' @param betain Initial beta
#' @param tauin Initial annotation coefficient
#' @param em_iterin EM iteration
#' @param mcmc_iterin MCMC iteration
#' @param min_degenein Minimum DE genes
#' 
#' @return A list
#' 
#' @export
EMMCMCStepSummary <- function(yin, varbetain, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein) {
    .Call(`_iDEA_EMMCMCStepSummary`, yin, varbetain, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein)
}

#' EM-MCMC with weight function based on summary statistics, effect size and variance of effect size
#' @param yin Estimated beta
#' @param varbetain Variance
#' @param weightin Weigth vector
#' @param Ain Annotation
#' @param betain Initial beta
#' @param tauin Initial annotation coefficient
#' @param em_iterin EM iteration
#' @param mcmc_iterin MCMC iteration
#' @param min_degenein Minimum DE genes
#' 
#' @return A list
#' 
#' @export
EMMCMCStepSummaryWeight <- function(yin, varbetain, weightin, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein) {
    .Call(`_iDEA_EMMCMCStepSummaryWeight`, yin, varbetain, weightin, Ain, betain, tauin, em_iterin, mcmc_iterin, min_degenein)
}

rcpp_hello_world <- function() {
    .Call(`_iDEA_rcpp_hello_world`)
}

